### ISSUE TITLE
Page about WG secretary

### ISSUE THREAD

**Issue by toerless** [ietf/chairs.ietf.org#11]
I think we should have a page explaining the role of WG secretary. 

One key section could be to promote the idea of secretary as a stepping stone towards role of WG chair. I think this is something some IESG member also wanted to promote in the recent past. That desire would be a good reason to have such a pafge to promote that idea and explain the role. Maybe not specific to secretary, but for both chair and secretary or the like.

The other key section is responsibilities, where i am not sure if we can only cite the litte that rfc2418 has to say, or also draft-secretaries-good-practices. Which never made it to RFC but IMHO still has useful content.

**Comment by ghwood** [comment]
I've added information here on the [organizing meetings](https://chairs.ietf.org/en/meetings) page with info about WG secretaries and other roles. Please feel free to add further detail.
