### ISSUE TITLE
Chairs slides template

### ISSUE THREAD

**Issue by dthaler** [ietf/chairs.ietf.org#14]
Specifically the note well slides.
During the WG chairs meeting it was pointed out that these are linked at the bottom of https://www.ietf.org/about/note-well/

However, I didn't notice them there, but looked at https://chairs.ietf.org/en/meetings under "Meeting planning templates, guides, and tools" but couldn't find them.

**Comment by ghwood** [comment]
addressed with [PR15](https://github.com/ietf/chairs.ietf.org/pull/15) which is now merged.
