### ISSUE TITLE
Pointer for "Non-Working Group Email List Guidelines"

### ISSUE THREAD

**Issue by paulehoffman** [ietf/chairs.ietf.org#27]
Chairs often are asked how to set up mailing lists for subgroups of their WG. A mention of the page for starting non-WG mailing lists, "Non-Working Group Email List Guidelines" at https://www.ietf.org/how/lists/nonwglist-guidelines/ should be added to `mailing-lists.md`.

**Comment by ghwood** [comment]
Done! https://chairs.ietf.org/en/mailing-lists Of course feel free to suggest improvements.
