### ISSUE TITLE
Does this have to be in it's own GitHub org?

### ISSUE THREAD

**Issue by larseggert** [ietf/chairs.ietf.org#4]
We have too many of those already. Can't it be under https://github.com/ietf?

**Comment by ghwood** [comment]
It can/should be, once it is in production--which should be in a few weeks.

**Comment by ghwood** [comment]
Hi @larseggert , this is ready to transfer to https://github.com/ietf but I [understand](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) either I need to have permissions to create repositories there or you need to have permissions for this repository to transfer it. 

Let me know which option you prefer (or if there's another I've missed).

**Comment by larseggert** [comment]
Jay is admin

**Comment by ghwood** [comment]
> @JayDaley could you pull this repo into the https://github.com/ietf organization please?

I've updated this repository's membership to make @JayDaley an owner so that request should be actionable now.
